name: Extraer playbackURL

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  extraer:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar página
        run: |
          curl -L "https://librefutbol.pe/embed/eventos.html?r=aHR0cHM6Ly9sYTEyaGQuY29tL3Zpdm8vY2FuYWwucGhwP3N0cmVhbT1lc3BucHJlbWl1bQ==" -o pagina.html

      - name: Extraer playbackURL
        run: |
          grep -oP 'playbackURL\s*=\s*"\K[^"]+' pagina.html > url.txt
          echo "URL encontrada:"
          cat url.txt

      - name: Guardar variable
        run: |
          URL=$(cat url.txt)
          echo "PLAYBACK_URL=$URL" >> $GITHUB_ENV
