name: Extraer listas premium

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Descargar HTML como navegador real
        run: |
          curl -L \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36" \
          -H "Accept-Language: es-ES,es;q=0.9" \
          https://spinoff.link/listas-premium/ \
          -o pagina.html

      - name: Extraer values
        run: |
          grep -oP 'class="caja-texto-copiar"[^>]*value="\K[^"]+' pagina.html > listas-premium.txt

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add listas-premium.txt
          git commit -m "Actualiza listas premium automático" || echo "Sin cambios"
          git push
