name: Sync M3U Files

on:
  push:
    branches:
      - cinecity.net   # ← tu branch real

permissions:
  contents: write   # ← ESTO SOLUCIONA EL 403

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy file
        run: |
          cp principal.m3u Alicia.m3u
          cp principal.m3u gabriela.m3u
          cp principal.m3u juanpablo.m3u
          cp principal.m3u mariano.m3u

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto sync M3U" || echo "No changes to commit"
          git push
